language: c

os:
 - linux
 - osx

env:
 - EXTRALIBS=""
 - EXTRALIBS="libusb-dev"
 - EXTRALIBS="libusb-1.0-0-dev libgd2-xpm-dev"

compiler:
 - clang
 - gcc

# Note: Keep the sudo commands in .travis.yml - they do not work from
#       a helper shell script.
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $(sh .travis-translate-pkgs $EXTRALIBS); fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/gettext/bin:$PATH; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y $(sh .travis-translate-pkgs $EXTRALIBS); fi

script:
  - autoreconf -v -i -f
  - ./configure --prefix=$PWD/_i
  - make && make check && make install && make installcheck

notifications:
  email:
    on_success: change
    on_failure: always
